# ted1k Docker image shared by all containers (php,python,shell scripts)
version: '2'
services:

  teddb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ted
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    logging:
      driver: json-file
      options:
        max-size: "2m"

  capture:
    build: ./go
    # replace these two lines to restpre pytho version of capture
    # build: .
    # command: python capture.py --forever --device /hostdev/ttyUSB0
    restart: unless-stopped
    links:
      - teddb
    volumes:
      # not used yet : /data/jsonl
      # - ./data:/data
      - /dev:/hostdev
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: "5m"

  summarize:
    build: .
    restart: unless-stopped
    command: python summarize.py --days 1 --forever
    links:
      - teddb
    logging:
      driver: json-file
      options:
        max-size: "2m"

  monitor:
    build: .
    restart: unless-stopped
    command: ./monitor.sh
    links:
      - teddb
    logging:
      driver: json-file
      options:
        max-size: "2m"

  publish:
    build: .
    restart: unless-stopped
    command: ./publish.sh
    links:
      - teddb
    logging:
      driver: json-file
      options:
        max-size: "2m"
    